project:
  type: website

website:
  title: "Kaushik Sinha"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/nasheqlbrm
      - icon: twitter
        href: https://twitter.com/_ksinha_
format:
  html:
    theme: cosmo
    css: styles.css



